---
# AUTHOR: KABBIL GI
# DATE: 28-11-2024

- name: Increase limits 
  hosts: all
  become: yes
  gather_facts: false
  vars:
    ansible_user: kabbil
    #user: 

  tasks:
    - name: Fail if limit_user is empty
      fail:
        msg: "user variable is required and cannot be empty"
      when: user is not defined
      tags:
        - always
        - add_nproc
        - add_nofile

    - name: Existing limits value 
      command: tail -n 5 /etc/security/limits.conf
      register: ans
      changed_when: false
      tags:
        - existing        
    
    - name: Existing sysctl value 
      command: cat /etc/sysctl.conf
      register: out
      changed_when: false
      tags:
        - existing
      
    - name: Debug Existing limits value 
      debug:
        var: ans.stdout_lines
      changed_when: false
      tags:
        - existing      
    
    - name: Debug Existing sysctl value
      debug:
        var: out.stdout_lines
      changed_when: false
      tags:
        - existing     

    - name: Set max process hard/soft limit
      blockinfile:
        path: /etc/security/limits.conf
        marker: "# {mark} ANSIBLE MANAGED NPROC {{ user }}"
        block: |
          {{ user }} hard nproc  320932
          {{ user }} soft nproc  320932
      tags:
        - add_nproc

    - name: Set max descriptors hard/soft limit
      blockinfile:
        path: /etc/security/limits.conf
        marker: "# {mark} ANSIBLE MANAGED NOFILE {{ user }}"
        block: |
          {{ user }} hard nofile 1048576
          {{ user }} soft nofile 1048576
      tags:
        - add_nofile

    - name: Set pid_max value
      sysctl:
        name: kernel.pid_max
        value: 2000000
        state: present
        sysctl_set: yes
      tags:
        - add_pid_max

    - name: Set threads-max value
      sysctl:
        name: kernel.threads-max
        value: 641864
        state: present
        sysctl_set: yes
      tags:
        - add_threads-max
        
    - name: Set vm.max_map_count value
      sysctl:
        name: vm.max_map_count
        value: 2048000
        state: present
        sysctl_set: yes
      tags:
        - add_vm_max_map_count

    - name: Set file-max value
      sysctl:
        name: fs.file-max
        value: 2000000
        state: present
        sysctl_set: yes
      tags:
        - add_file_max
 
    - name: Remove max process hard/soft limit
      blockinfile:
        path: /etc/security/limits.conf
        marker: "# {mark} ANSIBLE MANAGED NPROC {{ user }}"
        state: absent
      tags:
        - remove_nproc

    - name: Remove max descriptors hard/soft limit
      blockinfile:
        path: /etc/security/limits.conf
        marker: "# {mark} ANSIBLE MANAGED NOFILE {{ user }}"
        state: absent
      tags:
        - remove_nofile

    - name: Remove pid_max value
      sysctl:
        name: kernel.pid_max
        state: absent
      tags:
        - remove_pid_max   

    - name: Remove threads-max value
      sysctl:
        name: kernel.threads-max
        state: absent
      tags:
        - remove_threads-max
    
    - name: Remove vm.max_map_count value
      sysctl:
        name: vm.max_map_count
        state: absent
      tags:
        - remove_vm_max_map_count 

    - name: Remove file-max value
      sysctl:
        name: fs.file-max
        state: absent
      tags:
        - remove_file_max

    - name: Reload all sysctl settings after cleanup
      command: sysctl --system
      changed_when: true
      tags:
        - remove_pid_max
        - remove_threads-max
        - remove_vm_max_map_count
        - remove_file_max

    - name: updated limits value 
      command: tail -n 10 /etc/security/limits.conf
      changed_when: false
      register: ans
      tags:
        - updated
    
    - name: updated sysctl value 
      command: cat /etc/sysctl.conf
      changed_when: false
      register: out
      tags:
        - updated

    - name: Debug updated limits value 
      debug:
        var: ans.stdout_lines
      changed_when: false
      tags:
        - updated
    
    - name: Debug updated sysctl value
      debug:
        var: out.stdout_lines
      changed_when: false
      tags:
        - updated
    
    - name: Remove remote_tmp file
      file:
        path: /tmp/{{ansible_user}}
        state: absent
      tags:
        - cleanup
